version: '2'
services:
    celsales-app:
        image: celsales
        external_links:
            - celsales-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/celSales
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    celsales-postgresql:
        extends:
            file: postgresql.yml
            service: celsales-postgresql
