package com.mx.kiibal.celsales.domain.enumeration;

/**
 * The EstadoBateria enumeration.
 */
public enum EstadoBateria {
    BATTERY_HEALTH_COLD,BATTERY_HEALTH_DEAD,BATTERY_HEALTH_GOOD,BATTERY_HEALTH_OVER_VOLTAGE,BATTERY_HEALTH_OVERHEAT,BATTERY_HEALTH_UNSPECIFIED_FAILURE,BATTERY_HEALTH_UNKNOWN
}
